name: Deploy API
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/chasse-aux-sorcieres/api
            git pull origin main
            cd ..

            # 1. On build d'abord (ultra rapide maintenant grâce au cache)
            docker compose build api
            # 2. On applique le changement
            docker compose up -d api
            # 3. Nettoyage
            docker image prune -f
